# theme: jekyll-theme-minimal
minimal_mistakes_skin: "default" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"


# Name of website
title: Geodata Vizualizations
description: Geodata visualizations
name: Michael Davidson
pagination: true
paginate: 20

url: https://mdavidson.org/
baseurl: /geodata-viz

# Site Author / Left hand bar
author:
  name: "Davidson Lab"
  avatar: "/assets/img/MODIS_screenshot.png"
  bio: "Geospatial visualizations"
  home: https://mdavidson.org/


# --- Additional page parameters --- #

words_per_minute: 200


# --- Navigation bar options --- #

# List of links in the navigation bar
navbar-links:
  About: "readme"

# Image to show in the navigation bar - image must be a square (width = height)
# Remove this parameter if you don't want an image in the navbar
# avatar: ""

# If you want to have an image logo in the top-left corner instead of the title text,
# then specify the following parameter
# title-img: /path/to/image

# --- Footer options --- #

# Change all these values or delete the ones you don't want.
# Important: you must keep the "name" parameter, everything else you can remove
author:
  github: east-winds

# Select which links to show in the footer
footer-links-active:
  rss: false
  facebook: false
  email: false
  twitter: false
  google-plus: false
  github: true
  reddit: false
  linkedin: false
  xing: false
  stackoverflow: false
  snapchat: false
  instagram: false
  youtube: false
  spotify: false
  telephone: false

# Select which share links to show in posts
# share-links-active:
#   twitter: true
#   facebook: true
#   google: false
#   linkedin: true

# How to display the link to the website in the footer
# Remove this if you don't want a link in the footer
#url-pretty: "MyWebsite.com"

# --- Misc --- #
# Fill in your Disqus shortname (NOT the userid) if you want to support Disqus comments
#disqus: ""

# Google Tag Manager ID
#gtm: ""

# Facebook App ID
# fb_app_id: ""

# Excerpt Word Length
# Truncates the excerpt to the specified number of words on the index page
excerpt_length: 50

# Character used to separate site title and description in HTML document title
# and RSS feed title
title-separator: "-"

# --- Don't need to touch anything below here (but you can if you want) --- #

# Output options (more information on Jekyll's site)
timezone: "America/Los_Angeles"
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
markdown: kramdown
highlighter: rouge
permalink: /:year-:month-:day-:title/
paginate: 5

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

# Archives
#  Type
#  - GitHub Pages compatible archive pages built with Liquid ~> type: liquid (default)
#  - Jekyll Archives plugin archive pages ~> type: jekyll-archives
#  Path (examples)
#  - Archive page should exist at path when using Liquid method or you can
#    expect broken links (especially with breadcrumbs enabled)
#  - <base_path>/tags/my-awesome-tag/index.html ~> path: /tags/
#  - <base_path/categories/my-awesome-category/index.html ~> path: /categories/
#  - <base_path/my-awesome-category/index.html ~> path: /

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

compress_html:
  clippings: all
  ignore:
    envs: development


# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: # true
      share: true
      related: true